#!/bin/bash

# Description
# -----------------------------------
# Runs custom utility scripts located in a set directory
# $1 - The name the script
# -----------------------------------

# Config
# -----------------------------------
script_dir="$MY_SPACE/util-scripts"
# -----------------------------------

"$script_dir/$1"
